#!/bin/bash

set -euo pipefail

echo '--- Our hook'
env
ls -1
echo '--- Fetching real repo'
cd ${BUILDKITE_BUILD_CHECKOUT_PATH}
git remote set-url origin ${DYNAMIC_BUILD_REPO}
git clean -fxdq
git fetch -v --prune origin master
echo '--- Checking out hardcoded sha from pc pdf repo'
git checkout ${DYNAMIC_REF_SPEC}

export BUILDKITE_BRANCH="test"

