#!/bin/bash

set -euo pipefail

echo '--- Our hook'
env
ls -1
echo '--- clearing git folder'
cd ${BUILDKITE_BUILD_CHECKOUT_PATH}
rm -rf .git
cd ..
echo '--- Fetching real repo'
git clone git@github.com:certsy/certsy-lambda-police-check-certificate-generator.git ${BUILDKITE_BUILD_CHECKOUT_PATH}
cd ${BUILDKITE_BUILD_CHECKOUT_PATH}
