#!/bin/bash

set -euo pipefail

echo '--- Our hook'
env
ls -1
echo '--- Fetching real repo'
rm -rf "${BUILDKITE_BUILD_CHECKOUT_PATH}"
git init ${BUILDKITE_BUILD_CHECKOUT_PATH}
git remote add origin ${DYNAMIC_BUILD_REPO}
git fetch
echo '--- Checking out hardcoded sha from pc pdf repo'
git reset --hard ${DYNAMIC_REF_SPEC}

