#!/bin/bash

set -euo pipefail

BUILD_STEP_STATUS="pending"

echo '--- Fetching Build step status'

if [ ${BUILDKITE_COMMAND_EXIT_STATUS} == 0 ]
then
  if [ -n "${BUILD_SUCCESS}" ]
  then
    BUILD_STEP_STATUS="success"
  else
    BUILD_STEP_STATUS="pending"
  fi
else
  BUILD_STEP_STATUS="failure"
fi

echo '--- Payload for github status'

payload=$(cat <<EOF
{ \
  "state": "${BUILD_STEP_STATUS}", \
  "target_url": "https://buildkite.com", \
  "description": "Build status from buildkite", \
  "context": "certsy/lambda-build" \
}
EOF
)

echo ${payload}

echo '--- Posting build status...'

curl -v -u praveensastry:${GIT_ACCESS_TOKEN} https://api.github.com/repos/${GIT_ORG_NAME}/${GIT_REPO_NAME}/statuses/${GIT_REF_SPEC} \
-H "Content-Type: application/json" \
-d "$payload"
