#!/bin/bash

set -euo pipefail

echo '--- Posting build status...'

curl -u praveensastry:5cad067ccc7bf845356faac743b519673f137a90 https://api.github.com/repos/certsy/certsy-lambda-police-check-certificate-generator/statuses/f6b49ad728df094d1e5b412393a5169994bb6041 \
-X POST \
-d '{
  "state": "success",
  "target_url": "https://google.com",
  "description": "Manual status posting :rocket:",
  "context": "test context content"
}'