#!/bin/bash

set -euo pipefail

echo '--- Fetching Command exit status'

echo ${BUILDKITE_COMMAND_EXIT_STATUS}

echo '--- Posting build status...'

curl -u praveensastry:${GIT_ACCESS_TOKEN} https://api.github.com/repos/${GIT_ORG_NAME}/${GIT_REPO_NAME}/statuses/${GIT_REF_SPEC} \
-X POST \
-d '{
  "state": "success",
  "target_url": "https://google.com",
  "description": "Build Passed",
  "context": "certsy/lambda-build"
}'
